version: "3.8"
services:
  web:
    image: 127.0.0.1:5000/13112020:1.0
    build: .
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 5
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8000:8080
    depends_on:
      - db
volumes:
  db-data:
